# https://github.com/elastic/elasticsearch-docker
#FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
#FROM docker.elastic.co/kibana/kibana:7.16.0
FROM docker.elastic.co/elasticsearch/elasticsearch:7.16.0
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
