filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/suricata/eve.json

  fields:
    event.type: 

output.logstash:
  hosts: ["logstash:535"]
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]
  #ssl.certificate: "/etc/pki/client/cert.pem"
  #ssl.key: "/etc/pki/client/cert.key"
